### ISSUE TITLE
Can't use to open the external link

### ISSUE THREAD

**Issue by nisargpro** [glin94/external_link_account#1]
Hello i am try to open a link using this package and i am facing this issue when i run your example code.
i am using the latest flutter version
need help

**Comment by glin94** [comment]
Hi! Please, show your error logs

**Comment by glin94** [comment]
No further information

**Comment by nisargpro** [comment]
@glin94 hi sorry for the delay the issue is fixed as it was to do with Apple Account setup,

thank you.
